[package]
name = "rusty-gamepads"
version = "0.1.0"
authors = ["Lokathor <zefria@gmail.com>"]
repository = "https://github.com/Lokathor/rusty-gamepads"
readme = "README.md"
keywords = []
description = "Lets you use all sorts of gamepads."
license = "Unlicense"

publish = false

[lib]
name = "rusty_gamepads"
path = "src/lib.rs"

[dependencies]
log = "0.4"

[dev-dependencies]
simple_logger = "*"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["libloaderapi", "xinput", "winerror"] }
